# Generated by Django 5.0.4 on 2024-04-28 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagecontent",
            name="package",
        ),
    ]
